### ISSUE TITLE
Diagnose/fix throttle issue

### ISSUE THREAD

**Issue by jruths** [Nova-UTD/firmware#8]
From Jai on Teams:  

> "There seems to be a brake error. The parking break light is on and staying on, which means that there is a brake error or faulty parking brake switch. The parking brake switch seems to be working. We found that the brake lights won't turn on for some reason. This is apparently a common issue according to the internet. I'm not sure how to fix the brake system or lights. Also, the pedal is working as far as I can tell. "

"pedal is working" means that it is producing voltages when the pedal is pushed.

**Comment by jaiperis** [comment]
Update: 
We think we found the brake switch. We tried to read a voltage from the brake and got nothing. We also tried to send 12V to the brake switch and the lights did not turn on. This could mean there is some issue here or are test didn't work. We might need a certified technician :(

**Comment by jruths** [comment]
Relevant fuse box diagram to check the fuse:

![image](https://github.com/Nova-UTD/firmware/assets/11622384/1861df58-f567-45d4-9158-ef4c32c8cfd7)

**Comment by jruths** [comment]
Ok, I installed a new "resettable" 5A fuse. If this continues to trip, we need to look an an underlying cause.

**Comment by jruths** [comment]
I did confirm that the brake light goes off and the pedal now works.

**Comment by jaiperis** [comment]
This is good. I'll keep an eye on it to see if the fuse goes off again
