### ISSUE TITLE
Program LED matrices

### ISSUE THREAD

**Issue by danielv012** [Nova-UTD/firmware#9]

**Comment by meyli1** [comment]
https://www.instructables.com/64x32-RGB-LED-Matrix-With-Arduino-Mega/ -> programming with Arduino Mega

https://learn.adafruit.com/32x16-32x32-rgb-led-matrix/overview -> Adafruit Metro M0, Arduino Zero, Arduino Uno (32x16). Additional Wiring needed: Arduino Mega, Adafruit Metro M4

**Comment by Abhi220180** [comment]
Library and documentation for Arduino Uno : https://github.com/adafruit/RGB-matrix-Panel

**Comment by meyli1** [comment]
I have discovered while programming the matrix that in the workshop we only a pi, arduino uno, and adafruit metro (AT328) board. I noticed in several forums that the two microcontrollers i have been using don't have enough memory for the larger LED matrix panel that we have, so we can still use them in time for the parade (display word such as "HO! HO! HO!") the way it currently is; however, I will be working on getting it running on the Pi on thursdaay after i get a solution for the mounting. This is the forum that i used to come to this conclusion:  https://forums.adafruit.com/viewtopic.php?p=879945

**Comment by meyli1** [comment]
PI tutorial implementations:
- https://learn.adafruit.com/raspberry-pi-led-matrix-display/overview
- https://www.youtube.com/watch?v=9YG0_WbAxu8

**Comment by Fernando4242** [comment]
Program LED Matrices has included finding "permanent?" power sources for Raspberry Pi and LEDs. Then, for funsies talk between actions taken by the car show on the matrices "Turning Left" or "Turning Right". It's more like "Setup LED Matrix System"

**Comment by 5408Andy** [comment]
### 09/09/2024 Update:

- **Status:** Need to retrieve current code from Fern to continue progress on LED Matrices.
- - **Next Steps:** Send message to Fern to get the code and understand how far he got to completing the task and also understand his implementation.
- **Projected Completion:** Friday Sept 20
- **Update:**  Not much has happened for this task. Just need to put together a message.

**Comment by 5408Andy** [comment]
Reference Code for LED Matrices: [https://github.com/Nova-UTD/firmware/blob/main/matrices/matrix.py](https://github.com/Nova-UTD/firmware/blob/main/matrices/matrix.py)

**Comment by 5408Andy** [comment]
### 09/16/2024 Update:

- **Status:** Researching/Working on image upload feature. Also verify original operation of program.
- **Next Steps:** Keep working on the new feature...
- **Projected Completion:** Wednesday Sept 25
- **Update:**  Go through the old program and seeing how it worked. Also I am currently researching that image upload feature so we won't have to manual program a pixel map for new visuals. Nothing else much to be said...

**Comment by 5408Andy** [comment]
**Reminder for next update...**

- **Next Steps:** Need to also create better mounting solution for the Raspberry PI MCU rather than keeping the plastic tub (me and Ryan also looking into 3D printed solution that hooks to the 80/20 of the front rack).

**Comment by 5408Andy** [comment]
### 09/23/2024 Update:

- **Status:** Researching/Working on image upload feature. Also verify original operation of program.
- **Next Steps:** Fix read line issue and continue researching image upload feature.
- **Projected Completion:** TBD
- **Updates:** There was an issue of connecting to the serial setup, but I fix that. Here is a video showing that the matrices still work...

https://github.com/user-attachments/assets/bdbc8489-999a-401a-8ed3-fca3fd7851d3

**Comment by 5408Andy** [comment]
Still have yet to determine why the matrices 'glitch' every couple of seconds.

**Comment by 5408Andy** [comment]
### 10/13/2024 Update:

- **Status:** Got image upload feature working...
- **Next Steps:** Add more visuals that tells on lookers what the car is doing. Also start thinking about how the OBC is going to communicate to the PI (probably sending messages through ethernet like how I am doing now to display certain visuals).
- **Projected Completion:** TBD
- **Updates:** Fixed the issue where the PI would disconnect itself from its ethernet communication every 5 minutes. The cause of the glitches stemmed from some weird sound module on the PI.

https://github.com/user-attachments/assets/d7fde9f7-9e08-48e3-849e-1f77611eda72
https://github.com/user-attachments/assets/616fdf85-566d-49a6-9539-4f60f14029dc

**Comment by 5408Andy** [comment]
### 10/28/2024 Update:

- **Status:** Working on finalizing the Christmas Parade visuals for the LED matrix.
- **Next Steps:** Implement additional festive effects and refine the multi-file matrix runner for efficient control of different visuals.
- **Projected Completion:** TBD
- **Updates:** Added new visuals for the Christmas Parade, including snowflakes, rolling text, and Christmas-themed tree animations. Enhanced the matrix runner to switch between multiple visual scripts seamlessly. Multithreading has been implemented to improve smoothness of animations.


https://github.com/user-attachments/assets/afc0d0f3-1bbb-45b4-bf0d-54774ac31207
https://github.com/user-attachments/assets/293db0b4-8a3f-4d17-be67-8b826fcd6ad1

**Comment by 5408Andy** [comment]
### 11/10/2024 Update:

- **Status:** Switching functionality implemented.
- **Next Steps:** Remounting the LED matrices back to the car
- **Projected Completion:** TBD
- **Updates:** 
Text and Image Integration: Successfully resolved overlapping display issue between text and images on the LED matrices. Implemented a robust clearing mechanism to ensure smooth transitions.
Command Handling: Improved command parsing and response times for seamless status switching.
Thread Management: Enhanced thread synchronization to prevent residual artifacts or overlapping states on the matrix.

![Image](https://github.com/user-attachments/assets/edcc90dd-e1a2-4bf2-aff7-e90bb05165dc)

**Comment by 5408Andy** [comment]
### **11/18/2023 Update:**

- **Status:** Auto boot-up animation functionality completed  
- **Next Steps:** Reinstalling the LED matrices onto the cart in preparation for the Christmas parade  
- **Projected Completion:** TBD  

- **Updates:**  
**Auto Boot-Up Animation:**  
  Successfully configured the system to automatically launch and display the matrix animation upon boot. This ensures a hands-free startup, making the setup parade-ready.  
**Preparation for the Christmas Parade:**  
  The next step involves remounting the LED matrices onto the cart, finalizing the setup to bring festive cheer during the upcoming event. 
https://github.com/user-attachments/assets/f1a710e9-6db9-4a05-bcbf-65d80e4d546f

**Comment by 5408Andy** [comment]
https://github.com/user-attachments/assets/06baff0a-8460-46db-992d-8eaf9c71bc04

It is done.
